version: '3:8'
services: 
  app:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
        - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      - "MONGO_INITDB_DATABASE=mydb"
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=pass"
    command:
      mongod --quiet --logpath /dev/null
    
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      # - "RABBITMQ_ERLANG_COOKIE=secret cookie here"
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
      
    ports:
      - 15672:15672 #for user: guest pass: guest
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: madefire/chordtest
    command: celery worker --app=celery.celery --loglevel=info
    environment:
      - "CELERY_BROKER_URL=amqp://admin:admin@localhost:5672/rabbitmq"
      - "CELERY_BROKER_BACKEND=mongodb://root:password@27017/mydb"
      - "C_FORCE_ROOT=true"

    volumes:
      - .:/app/
    depends_on:
      - rabbitmq
      - mongodb
  
  # flower:
  #   container_name: flower
  #   build: .
  #   command: celery -A celery flower --port=5555
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #     - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  #   depends_on:
  #     - app
  #     - 
  #     - worker