version: '3:8'
services: 
  app:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
        - mongodb

  # db:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data:/data/db

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      - "MONGO_INITDB_DATABASE=mydb"
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=pass"
      # - "MONGO_URI=mongodb://{MONGO_USER}:${MONGO_PASS}@mongo:27017/"

    command:
      mongod --quiet --logpath /dev/null
    

  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      - "RABBITMQ_ERLANG_COOKIE=secret cookie here"
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
      
    ports:
      - 15672:15672 #for user: guest pass: guest